name: paysage-classification
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - expat=2.7.3
  - ffmpeg=6.1.1
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fsspec=2025.10.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - kiwisolver=1.4.8
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.8.2
  - libcups=2.4.2
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtheora=1.2.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mesalib=25.1.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - ncurses=6.5
  - networkx=3.5
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.0.18
  - opentelemetry-api=1.37.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=11.1.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.23
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pytz=2025.2
  - pyyaml=6.0.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sleef=3.5.1
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - sympy=1.14.0
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wayland=1.24.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - bleach==6.3.0
      - joblib==1.5.2
      - kaggle==1.7.4.5
      - protobuf==6.33.0
      - python-slugify==8.0.4
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - webencodings==0.5.1
prefix: /home/andrey/miniconda3/envs/paysage-classification
